name: chatbot_gemini
description: "Chatbot Gemini is a Flutter package that provides a chatbot widget
  for your Flutter app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dash_chat_2: ^0.0.20
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
